name: CI

on:
  push:
    branches:
      - "*"
      - "!gh-pages"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  project-test:
    runs-on: ubuntu-20.04
    env:
      INCI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          distribution: "oracle"
          java-version: "8"
      - run: make setup-prod
      - run: make build
        if: ${{ !cancelled() }}
      - run: make check-tidy
        if: ${{ !cancelled() }}
